### ISSUE TITLE
Add documentation for the vision and progress of the library

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#111]
What is the end state of the library?
What we aim to support, what do we exclude support for?
How is the library intended to be used?

**Comment by andorsk** [comment]
Thanks @decentralgabe for adding this in. 

I can tell you for me this is personally pretty important. l help put together the documentation, but bluntly I am trying to understand how much I should bank on the SSI-SDK to leverage for my project vs. what I need to be building myself. Understanding the vision of this project is imperative to making this happen.

**Comment by andorsk** [comment]
This seems to start getting more and more important as time goes on. @decentralgabe what do you think is best way to move this ticket forward? I can maybe submit a draft PR and we can work off of it?

**Comment by decentralgabe** [comment]
Hi @andorsk happy to get a draft PR. I plan on taking it after my presentation exchange PR.

**Comment by decentralgabe** [comment]
Fixed in #173
