### ISSUE TITLE
Add docstring to JSONWebKeySigner

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/ssi-sdk#112]
Suggestion to add documentation to the struct JSONWebKeySigner: https://github.com/TBD54566975/ssi-sdk/blob/main/cryptosuite/jsonwebkey2020.go#L350 and JSONWebKeySigner as well.

**Comment by decentralgabe** [comment]
Fixed in https://github.com/TBD54566975/ssi-sdk/pull/118
