### ISSUE TITLE
Produce WASM JS bindings

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/ssi-sdk#119]
leveraging the functionality provided by SSI SDK in JS/TS projects would be very helpful. We can produce JS bindings using [syscall/js](https://pkg.go.dev/syscall/js) and compiling to WASM. I think it'd be awesome if we:
* shipped the bindings as a consumable lib
* included automated tests for said bindings that run in a headless browser
* leveraged CI to automatically compile, package, and upload the bindings as an npm module

wondering if it makes most sense for the bindings to live in this repo or in a separate repo.

**Comment by andorsk** [comment]
I did some tests around WASM today for personal understanding. WASM is SO cool! I love it. @mistermoe are there any big concerns around using WASM in production for this use case that needs to be brought to light?

**Comment by andorsk** [comment]
Linking some stuff here on my research:
![image](https://user-images.githubusercontent.com/8604639/187788941-1f2a015c-b420-4ba2-9f1a-82104818f7c0.png)

**Comment by decentralgabe** [comment]
This is handled https://github.com/TBD54566975/ssi-sdk/tree/main/wasm
