### ISSUE TITLE
Release Cycle?

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/ssi-sdk#122]
Simple Question: @decentralgabe what's the release cycle of this repo?

Includes:

1. Release schema
2. Release documentation
3. Release frequency

**Comment by decentralgabe** [comment]
it's a good question. I imagine once https://github.com/TBD54566975/ssi-sdk/milestone/2 is complete we can release the first "alpha" version. However, this is a good item to add to the documentation for the repo, so I'll track it.

Thanks for raising!
