### ISSUE TITLE
bug: some did:web tests failing: `TestDIDWebGetURL` and `TestDIDWebResolve`

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/ssi-sdk#124]
Expected: All tests pass
Actual:
```
=== RUN   TestDIDWebGetURL
ERRO[0000]                                               error="DIDWeb did:key:z6MkiTBz1ymuepAQ4HEHYSF1H8quG5GLVVQR3djdX3mDooWp is missing prefix did:web:"
--- PASS: TestDIDWebGetURL (0.00s)
=== RUN   TestDIDWebResolve
ERRO[0001] could not resolve with docURL https://doesnotexist.com/.well-known/did.json  error="Get \"https://doesnotexist.com/.well-known/did.json\": x509: “*.netlify.app” certificate name does not match input"
ERRO[0001] could not resolve DIDWeb did:web:doesnotexist.com  error="Get \"https://doesnotexist.com/.well-known/did.json\": x509: “*.netlify.app” certificate name does not match input"
```

Steps to reproduce:

Commit: 6ea3dcab34ad4b82a03efb16786dfbfbb49e40dc
```
cd did
go test -v
```

**Comment by singyiu** [comment]
@andorsk 
this is the expected error (part of the test), for case that a non-resolvable DIDWeb is used.
The test is actually passing correctly.

**Comment by andorsk** [comment]
Ah: Thanks @singyiu. Sorry about that. I misunderstood.  I'll close this issue. 

One thing, which I'll bring up with @decentralgabe is that I how we are logging errors throughout the codebase. We should be propagating the errors throughout the code base and handling them at the very end in terms of logging. Then these tests would run clean unless you decided to explicitly log the error after catching. I've noticed it throughout the codebase. 

https://levelup.gitconnected.com/go-error-best-practice-f0864c5c2385

```The bottom method returns errors, while the upper method handles the errors.```

**Comment by decentralgabe** [comment]
> Ah: Thanks @singyiu. Sorry about that. I misunderstood.  I'll close this issue. 
> 
> 
> 
> One thing, which I'll bring up with @decentralgabe is that I how we are logging errors throughout the codebase. We should be propagating the errors throughout the code base and handling them at the very end in terms of logging. Then these tests would run clean unless you decided to explicitly log the error after catching. I've noticed it throughout the codebase. 
> 
> 
> 
> https://levelup.gitconnected.com/go-error-best-practice-f0864c5c2385
> 
> 
> 
> ```The bottom method returns errors, while the upper method handles the errors.```
> 
> 

Generally agree, yes. However ideally we add some more logging and any consumers are able to set the log level they desire, this can give a bit more insight into a potential issue than a log line purely at the call site.

**Comment by andorsk** [comment]
@decentralgabe agreed users should be able to set the log level per desire. But i'd suggest for errors specifically we propagate them them at the end. DEBUG and INFO level it's fine to write them directly in the methods. 

Imagine we have hundreds of tests with failure cases. Our tests will be unreadable with tons of errors being thrown over logging as errors are shown by `go test` by default.

**Comment by andorsk** [comment]
One other thought here is somehow we see about removing error from the `go test` output. That might be a reasonable solution as well.

**Comment by decentralgabe** [comment]
> One other thought here is somehow we see about removing error from the `go test` output. That might be a reasonable solution as well.
> 
> 
> 
> `log.SetOutput(ioutil.Discard)` maybe?

I'd welcome this as a PR I think it's a great idea. Changing all log lines here to info or debug would be welcome as well.

**Comment by decentralgabe** [comment]
@andorsk created https://github.com/TBD54566975/ssi-sdk/issues/136 to track logging
