### ISSUE TITLE
feat: global logger across ssi-sdk

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/ssi-sdk#125]
Suggestion here to have a global logger that allows us to handle/control logging for the entire ssi-sdk. This includes actions such as formatting and levels. 

All existing code should be refactored to work with the global logger.

**Comment by decentralgabe** [comment]
Logrus is the global logger: https://github.com/sirupsen/logrus

Logrus is nice in the sense that you can define logrus config in any consuming project, and it'll apply to the SDK as well.

Does this address your concern? Would more documentation around the usage of logrus help?

**Comment by andorsk** [comment]
First wanted to mention this: https://github.com/TBD54566975/ssi-sdk/issues/136 as it seems closely related. 

And i think we need an abstraction of a logger. I've used logrus a ton, but we need to have an actual `logging` instance where we can configure logrus and other loggers more safely. 

It could be simply a wrapper in a `logger.go` file? If we ever wanted to strip out logrus later, we wouldn't have to refactor the entire codebase to do so.

**Comment by decentralgabe** [comment]
Sure, I'm going to close this issue in favor of #136 and move your comment there.
