### ISSUE TITLE
Run CI on a regular schedule.

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#135]
Noticed that one of the deps of this project changed and broke, not detected by CI. Caused: https://github.com/TBD54566975/ssi-sdk/pull/133

The ask is to run CI at least once a day, as a CRON job. This should be [simple to configure using github actions](https://docs.getnacelle.com/deployment/scheduled-builds-github-actions.html).

**Comment by nitro-neal** [comment]
Pr here - https://github.com/TBD54566975/ssi-sdk/pull/166

**Comment by decentralgabe** [comment]
Fixed in #166
