### ISSUE TITLE
Constraints should be Constraint

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/ssi-sdk#151]
Rename Constraints to Constraint: 

https://github.com/TBD54566975/ssi-sdk/blob/e2fdcfb80e4907ac956c40db40e19570c5e87ec7/credential/exchange/model.go#L225

**Comment by decentralgabe** [comment]
It is named as such according to the spec: https://identity.foundation/presentation-exchange/#input-descriptor-object

**Comment by andorsk** [comment]
@decentralgabe thanks. My apologies. You're correct. I will close this ticket.
