### ISSUE TITLE
JWT from existing DID private key

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/ssi-sdk#160]
There are use cases where we need to get a JWT from an existing DID private key. 

We should make a function in jsonwebkey2020.go file

The function will have some similar functionality to this: https://github.com/TBD54566975/ssi-sdk/blob/main/cryptosuite/jsonwebkey2020.go#L178

It should look like this:
didPrivKey, didKey, err := did.GenerateDIDKey(crypto.Secp256k1)
jwtPrivKey = getJwtKey(didPrivKey)

**Comment by nitro-neal** [comment]
PR - https://github.com/TBD54566975/ssi-sdk/pull/161

**Comment by decentralgabe** [comment]
Fixed in #160
