### ISSUE TITLE
Support the generation of DID Well Known Configuration Documents

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#162]
As per https://identity.foundation/.well-known/resources/did-configuration/

The generation of .well-known files in accordance with the specification to advertise or link a DID to a website.

**Comment by decentralgabe** [comment]
@nitro-neal can this be closed?

**Comment by nitro-neal** [comment]
There is another task for API endpoint, so will close this

**Comment by decentralgabe** [comment]
@nitro-neal please note the task here!
