### ISSUE TITLE
did:key interoperability suite support

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#176]
This library has an implementation of `did:key`. It should be added to the suite in the W3C CCG for interoperability testing.

https://w3c-ccg.github.io/did-key-test-suite/

**Comment by decentralgabe** [comment]
Note: this requires a hosted version of the SSI SDK

**Comment by decentralgabe** [comment]
In accordance with the latest draft of the spec our impl will need to switch to using JWK keys.

**Comment by nitro-neal** [comment]
Will use code that looks something like this:
```
		privJWK, err := crypto.PrivateKeyToJWK(privKey)
		if err != nil {
			return generateError(err)
		}

		pubJWK, err := crypto.PublicKeyToJWK(pubKey)
		if err != nil {
			return generateError(err)
		}
```

**Comment by decentralgabe** [comment]
passing test vectors with this https://github.com/TBD54566975/ssi-sdk/pull/382

**Comment by decentralgabe** [comment]
Going to close this because I don't like that the test suite requires you have a running server. If they remove that requirement we can reconsider. For now, compliance with the test vectors is more than sufficient.
