### ISSUE TITLE
[Bug] x/mobile: API containing unsupported types

### ISSUE THREAD

**Issue by nrobi144** [TBD54566975/ssi-sdk#181]
**Describe the bug**
As `gomobile` currently supports [these types only](https://pkg.go.dev/golang.org/x/mobile/cmd/gobind#hdr-Type_restrictions),   most of the API layer is skipped when mobile binaries are produced

(See the attached screenshot or `Crypto.java` gist below)

**To Reproduce**
1. Run `mage android`
2. Check out the generated `Crypto.jar`

Alternatively, you can clone this repo https://github.com/nrobi144/ssi-sdk-demo-android and open the `Crypto.java` file in an IDE

**Expected behavior**
The core functionality of the `crypto` package should be available to me (`GenerateKeyByKeyType()` for example)

**Supporting Material**
[Crypto.java ](https://gist.github.com/nrobi144/5ac344ca1fdd7958993917229ea2371b)

![Screenshot 2022-09-02 at 14 27 51](https://user-images.githubusercontent.com/68047666/188129899-5eb22812-30ae-43f3-bc83-8db81b901e26.png)

**Additional context**
Solutions I can think of:
1. Work within the boundaries of `gomobile`'s [Type Restrictions](https://pkg.go.dev/golang.org/x/mobile/cmd/gobind#hdr-Type_restrictions)
2. Mirror `ssi-sdk` in a `ssi-sdk-mobile` repo
3. Consider alternatives to `gomobile` for producing mobile binaries

**Comment by decentralgabe** [comment]
What do you think about adding a `ssi-sdk-mobile` that wraps the `ssi-sdk` methods and changing the type parameters as necessary?

Alternatively, this can be done within a `mobile` package in the `ssi-sdk` itself.

**Comment by nrobi144** [comment]
> What do you think about adding a `ssi-sdk-mobile` that wraps the `ssi-sdk` methods and changing the type parameters as necessary?
> 
> Alternatively, this can be done within a `mobile` package in the `ssi-sdk` itself.

@decentralgabe that is a good idea! I'll play around with that

**Comment by nrobi144** [comment]
@decentralgabe @nitro-neal I see multiple usages of "type-alias like definitions". For ex.
```
type (
	Proof              interface{}
	KeyType            string
	SignatureAlgorithm string
)

const (
	Ed25519   KeyType = "Ed25519"
	X25519    KeyType = "X25519"
	Secp256k1 KeyType = "secp256k1"
	P224      KeyType = "P-224"
	P256      KeyType = "P-256"
	P384      KeyType = "P-384"
	P521      KeyType = "P-521"
	RSA       KeyType = "RSA"

	RSAKeySize int = 2048
)
```

Is there a way to minimise and remove these going forward? I'm assuming these are not just type aliases as in that case `gomobile` should be able to replace them with `string` (pardon my lack of Go knowledge)

Context: I'd like [ssi-sdk-mobile](https://github.com/nrobi144/ssi-sdk-mobile) to be as minimal as possible, while `gomobile` doesn't cause any quality losses for the sdk.

**Comment by nrobi144** [comment]
So upon further research, my understanding is that `type KeyType string` might be an Enum definition.

I've just tried replacing it with
```
type KeyType struct {
	value string
}

const (
	Ed25519   string = "Ed25519"
	X25519    string = "X25519"
	Secp256k1 string = "secp256k1"
	P224      string = "P-224"
	P256      string = "P-256"
	P384      string = "P-384"
	P521      string = "P-521"
	RSA       string = "RSA"

	RSAKeySize int = 2048
)

func GetSupportedKeyTypes() []KeyType {
	return []KeyType{{Ed25519}, {X25519}, {Secp256k1}, {P224}, {P256}, {P384}, {P521}, {RSA}}
}
```

It seems that `GetSupportedKeyTypes()` is still not generated for Android. See [Crypto_sep6.java](https://gist.github.com/nrobi144/b0dc0de15ded357005bf105e3bb2e400)

**Comment by decentralgabe** [comment]
@nrobi144 it is indeed an alias. I see how it's causing issues. I think it may be best to make a mapping function in the wrapper lib. 

I tried to replicate your steps and noticed that I did not have the Android SDK installed, or NDK/cmake. It may be worth updating the mage commands, or at least the docs to note this as a prerequisite for Android.

I put together a small draft, which isn't working but I think it's on the right track. I did not have enough time to see this through but I hope it's helpful - and I'll be able to pick it up soon. https://github.com/TBD54566975/ssi-sdk/pull/184/files. Notably you need to add `./` before the package. The errors you see are trying to generate the go standardlib for `crypto` instead of the local crypto package for this project which can be generated with `./crypto`.

I'm not certain why the new methods aren't being generated properly. I'm following the [rules here](https://pkg.go.dev/golang.org/x/mobile/cmd/gobind) around only returning one or two values, and basic types. 🤔

**Comment by nrobi144** [comment]
>I'm not certain why the new methods aren't being generated properly. I'm following the [rules here](https://pkg.go.dev/golang.org/x/mobile/cmd/gobind) around only returning one or two values, and basic types. 🤔

It seems like structs need to be returned as pointers

**Comment by decentralgabe** [comment]
@nrobi144 shall we keep this open to continue discussing mobile issues as they come up, or ok to close?

**Comment by nrobi144** [comment]
> @nrobi144 shall we keep this open to continue discussing mobile issues as they come up, or ok to close?

@decentralgabe I'll close it for now and open more specific issues for mobile as they come up. Maybe a *mobile label* would be a good idea?

**Comment by decentralgabe** [comment]
added
