### ISSUE TITLE
[Idea] Selective Disclosure with JWT-SD

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#197]
**Is your feature request related to a problem? Please describe.**
We don't have a method to do selective disclosure!

**Describe the solution you'd like**
Using https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.htmlto add in a simple selective disclosure scheme.

**Describe alternatives you've considered**
BBS+, SPARTAN.
BBS+ has some impls, but needs substantial work/research to integrate here.
SPARTAN is still a WIP.

**Getting it done**
Nice to have, not immediately urgent. Happy to take this myself.

**Comment by andresuribe87** [comment]
Closing as fixed by #288 and #369
