### ISSUE TITLE
[Idea] dynamic bytes to public/private key

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/ssi-sdk#205]
**Is your feature request related to a problem? Please describe.**

Thought here: Instead of specifying the Key Type directly to convert from bytes to public key, loop through the supported key types to "guess" the correct key type. i.e Given some byte array of a key, convert it into a crypto key. 

*A clear and concise description of what the problem is. Ex. I'm frustrated when [...]*
You need to know the KeyType a priori with the BytesToPubKey and BytesToPrivateKey method. 

**Describe the solution you'd like**
something like this: 
```
func ConvertPrivateBytesToKey(d []byte)(crypto.PrivateKey, error){
    // attempts to determine key
}
```

**Describe alternatives you've considered**
I can write it myself if needed, but that's the alternative. 

**Getting it done**

*Are you building this yourself? Do you need help? What is the urgency of the feature? What are the next steps?*
I can build it if it make sense. Wanted some feedback first.

**Comment by andorsk** [comment]
@decentralgabe wanted some thoughts here. Am I missing something or is this reasonable?

**Comment by decentralgabe** [comment]
I don't know if guessing the key type based on bytes is reasonable, there can be overlap. For example, both `secp256k1` and `ed25519` keys can be 32 bytes long. I'm sure there are other cases.

**Comment by andorsk** [comment]
Yep...that makes sense. Thanks for the clarity. Will close.
