### ISSUE TITLE
Figure out how to cache & load LD-Contexts

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#26]
LD Contexts should be loaded and cached without making web requests. Web servers go down, and when they do, they shouldn't stop us from verifying data. I'm not sure if this is a capability of https://github.com/piprate/json-gold

**Comment by georgejpadayatti** [comment]
Also, it adds an additional latency if there is no cache support. Facing the same problem in a project that I am working. 
https://github.com/decentralised-dataexchange/acapy-mydata-did-protocol

**Comment by singyiu** [comment]
[PR](https://github.com/TBD54566975/ssi-sdk/pull/102)

[json-gold](https://github.com/piprate/json-gold) does have the caching document loader implemented (RFC7324)
It is enabled by passing the caching loader into the ldProcessor options
Added it as the default option [here](https://github.com/singyiu/ssi-sdk/blob/c1f4324e9d365481dde54b47af76be47e0f82b67/util/helpers.go#L44).

Json-ld context can be loaded as a json-ld document (type map[string]interface{}) using the loadDocument function [test example](https://github.com/singyiu/ssi-sdk/blob/c1f4324e9d365481dde54b47af76be47e0f82b67/util/helpers_test.go#L115)
or further converting it into a json-gold.Context object [test example](https://github.com/singyiu/ssi-sdk/blob/c1f4324e9d365481dde54b47af76be47e0f82b67/util/helpers_test.go#L134)
A helper function "GetContextFromMap" was added.

**Comment by decentralgabe** [comment]
Fixed in #102
