### ISSUE TITLE
[Idea] DID Document Builder

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/ssi-sdk#283]
**Is your feature request related to a problem? Please describe.**
Similar to how there is a VerifiableCredential builder: https://github.com/TBD54566975/ssi-sdk/blob/main/credential/builder.go#L24, I think it would be helpful to also have a DIDDocument builder. 

**Describe the solution you'd like**
Similar implementation to the VerifiableCredentialBuilder, but for DIDDocuments.

**Describe alternatives you've considered**
The alternative is to just expect to add methods via the struct. 

**Getting it done**
I'm considering building this out. If I do want to do this, I can contribute a PR to do this.

**Comment by decentralgabe** [comment]
Done in #284
