### ISSUE TITLE
Add coding guidelines to contribution document

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-sdk#290]
In order to ensure code is easy to maintain and modify, I propose we add the following guidelines:

1. All new code and PRs should follow Uber's Go Style guide: https://github.com/uber-go/guide/blob/master/style.md
2. All new tests should follow unit test best practices from MSFT: https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#best-practices

If we're in agreement, I can add a PR for this.

**Comment by decentralgabe** [comment]
Agree, would be great to get this codified.
