### ISSUE TITLE
did:ion support

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#30]
Able to create/resolve ION DIDs and use their keys for signing/verification

**Comment by csuwildcat** [comment]
I need this in the next few weeks, so hopefully we're not going to have someone recreating the ION Tools/SDK lib. This is now priority, because we have our Desktop Identity app and two outside developers who need legit DIDs to use.

**Comment by decentralgabe** [comment]
multi language support is a strength; necessary to facilitate interop.

in the meantime we can consume the existing lib to not block the work from progressing.

**Comment by decentralgabe** [comment]
should take a look at existing go impls:
- https://github.com/trustbloc/sidetree-core-go
- https://github.com/hyperledger/aries-framework-go/blob/8771727477195b73d8e9ba5194be535b928afcda/test/bdd/pkg/sidetree/sidetree.go

**Comment by decentralgabe** [comment]
Done in https://github.com/TBD54566975/ssi-sdk/pull/318 and #307
