### ISSUE TITLE
[Idea] Consider replacing {Public,Private}KeyJWK in favor of jwx.Key

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-sdk#309]
Creating issue from https://github.com/TBD54566975/ssi-sdk/pull/308#discussion_r1142379868

Some considerations:
* Should we decouple our SDK from dependencies like lestrat-go?
* If so, de we want to implement the JWK standard? Should we do that as a separate project?

**Comment by decentralgabe** [comment]
we should rely upon widely used (successful open source projects!) as much as possible.

it follows we should roll off our bespoke impls as much as possible. if we can feasible just use jwx.Key we should.

**Comment by decentralgabe** [comment]
Closing, as we've decided to fully decouple key usage from the JWX lib, as is a necessity for using keys not supported by the lib.
