### ISSUE TITLE
[Bug] mage android is an invalid target

### ISSUE THREAD

**Issue by haarts** [TBD54566975/ssi-sdk#320]
**Describe the bug**
The build target 'android'/'ios' do not work.

```
Unknown target specified: "android"
```

**To Reproduce**

1. Clone the repo
2. run `mage android`

**Expected behavior**

Since I'm running Linux I never expect iOS to work, so Android only for me. 

**Environment (please complete the following information):**

- OS: Linux  5.19.17-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Nov 6 00:08:27 UTC 2022 x86_64 GNU/Linux
- Go: 1.20

**Comment by haarts** [comment]
PS This log line reads `iOS` where it should read `Android`: https://github.com/TBD54566975/ssi-sdk/blob/main/magefile.go#L364

**Comment by haarts** [comment]
I've hacked a new build target in the mage file to get Android to build. That works but the build ultimately fails with: 

```
❯ mage foo
Building Android - API Level: 23...
Building [crypto] package...
Building [did] package...
gomobile: /home/harm/go/bin/gobind -lang=go,java -outdir=/tmp/gomobile-work-4274079403 did failed: exit status 1
no exported names in the package "did"
no exported names in the package "did"
no exported names in the package "did"
no exported names in the package "did"

FATA[0004] Error building Android pkg: did               error="running \"gomobile bind -target android -androidapi 23 did\" failed with exit code 1"
```

**Comment by decentralgabe** [comment]
Thanks @haarts that error looks correct. I'm wondering if it's best to remove the mage commands for ios and android in favor of our mobile SDK specific repo. What do you think @shamilovtim?

**Comment by shamilovtim** [comment]
> Thanks @haarts that error looks correct. I'm wondering if it's best to remove the mage commands for ios and android in favor of our mobile SDK specific repo. What do you think @shamilovtim?

That makes sense for now

**Comment by decentralgabe** [comment]
https://github.com/TBD54566975/ssi-sdk/pull/324
