### ISSUE TITLE
Generic "Resolvers"

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#38]
Create generic resolvers for certain data types, like DIDs, Schemas, Revocations.

Provide an interface with an in-memory implementation at the minimum. A HTTP implementation might also be worth it.

**Comment by andorsk** [comment]
YES! this is needed. The more I've played with the SDK, the more I've realized this is a kinda big problem that needs to be resolved. 

A question also begs which is how we interact with the ecosystem in general. See https://github.com/decentralized-identity/universal-resolver as an example

TBH I'm not a huge fan of the above. It's way to heavyweight for what it's trying to do. Maybe there's a middle ground?

**Comment by peacekeeper** [comment]
Hello I have a few thoughts on this.

I think it would be very useful to work on integrating ssi-sdk and ssi-service with both the Universal Resolver (https://github.com/decentralized-identity/universal-resolver) and the Universal Registrar (https://github.com/decentralized-identity/universal-registrar). The latter is a not-so-well-known project, but it's essentially the same idea, creating an abstraction layer not only for the DID resolve operation, but also for the create/update/deactivate operations.

With regard to "heavyweight". Yes. Both the Universal Resolver and Universal Registrar are rather heavy-weight container-based applications, so you definitely can't run them on a mobile phone, etc. They are run as services, and therefore can also add an element of centralization that DIDs are not supposed to have.

But, the purpose of these components is still a bit more nuanced than it seems:
- First, they are based on open specifications ([DID Resolution](https://w3c-ccg.github.io/did-resolution/), [DID Registration](https://identity.foundation/did-registration/)) which do not mandate any specific implementation or deployment pattern. They define abstract interfaces that can be implemented in various ways.
- Second, both the Universal Resolver and Universal Registrar can be self-hosted. If you are planning to run something like TBD's ssi-sdk or ssi-service on some backend service, then I think there's nothing wrong with also deploying the Universal Resolver/Registrar side-by-side with that.
- Third, we often see deployment patterns where some DID methods are implemented as part of a local library, and remote Universal Resolver/Registrar services are configured as "fallbacks" when the local library can't handle a certain DID method. For example, TBD's ssi-sdk could handle did:key internally (no need to use any external component), but it could use the Universal Resolver/Registrar for handling did:ebsi or did:indy or did:v1, etc.

This should be configurable, in a similar way as you can configure your DNS server in your operating system. Depending on requirements, TBD's ssi-sdk or ssi-service could be configured to handle all DID operations internally, or use a self-hosted instance of the Universal Resolver/Registrar, or in certain situations perhaps even use a commercial, centralized service such as https://godiddy.com/ (maybe only for testing/development purposes).

The advantage would be that the TBD tools could immediately benefit from supporting many different DID methods (resolve/create/update/deactivate) out-of-the-box.

I'd love to discuss this more if there is an opportunity?

**Comment by andorsk** [comment]
Good thoughts here @peacekeeper (btw I've seen some of your presentations ). Thank you for them. Great stuff.  

@decentralgabe I think this closely relates to: https://github.com/TBD54566975/ssi-sdk/issues/111. In fact, I would argue this ticket is "blocked" until https://github.com/TBD54566975/ssi-sdk/issues/111 is somewhat more hashed out. 

@peacekeeper To your second and third point. I'm not sure this is always intended to be hosted as a service? Again, https://github.com/TBD54566975/ssi-sdk/issues/111 really matters here. 

Re: services configured as "fallbacks", definitely I think it should be configurable, and to your point maybe the ecosystem will eventually have various commercial DID Resolvers. That being said: I would generally prefer NOT using a resolver if I could avoid it, as that somewhat requires trust on behalf of the resolving party, which is a failure point. 

Again, all falls back to  https://github.com/TBD54566975/ssi-sdk/issues/111. Right now we support did:key, did:peer, and did:web. What's the scope here for future did methods? 

Finally, I'd like to point out a recent: https://github.com/TBD54566975/ssi-sdk/blob/main/did/interface.go#L30 resolver interface. In theory, we can add a whole bunch of methods as long as it supports the DID resolution interface. 

A question here is: Are there any other requirements for a DID Resolver that haven't been specified?

**Comment by peacekeeper** [comment]
> Right now we support did:key, did:peer, and did:web.

I have a question about this, I thought the web5 project was primarily based on `did:ion`, did I misunderstand that? I would have expected there to be code for `did:ion` in ssi-sdk or ssi-service.

> Finally, I'd like to point out a recent: https://github.com/TBD54566975/ssi-sdk/blob/main/did/interface.go#L30 resolver interface.

Good start, but it's missing some things that you can have in DID resolution, see the DID Core spec for the [abstract function definition](https://www.w3.org/TR/did-core/#did-resolution): 

```
resolve(did, resolutionOptions) →
   « didResolutionMetadata, didDocument, didDocumentMetadata »
```

> Are there any other requirements for a DID Resolver that haven't been specified

In general, most of the requirements/considerations should be expressed in the (still work-in-progress) DID Resolution spec (https://w3c-ccg.github.io/did-resolution/). Maybe one thing to mention is that there's DID resolution, and then there's also DID URL dereferencing.

My understanding from last IIW was that there are some interesting applications of DID URLs (DID with path and/or query and/or fragment) in DWNs.

**Comment by andorsk** [comment]
Added an issue here: https://github.com/TBD54566975/ssi-sdk/issues/new

**Comment by cihanss** [comment]
@peacekeeper
> I have a question about this, I thought the web5 project was primarily based on did:ion, did I misunderstand that? I would have expected there to be code for did:ion in ssi-sdk or ssi-service.

The default method supposed to be ION, as it is stated [here](https://github.com/TBD54566975/tbdex-whitepaper/issues/11#issuecomment-983139664). However, ION support is not [there](https://github.com/TBD54566975/ssi-sdk/issues/30) yet.

**Comment by peacekeeper** [comment]
Sounds like we're aligned. +1 to making the stack unopinionated and supporting any DID method. If we all follow a standardized DID resolution interface, it should be possible to just "plug in" support for different DID methods. Ideally locally as part of the ssi-service itself, but various options to plug in existing resolvers are also possible.

And yes I agree multiple implementations are a good thing, also for standardization processes, test suites, etc.

**Comment by decentralgabe** [comment]
Brief update: we (TBD) discussed as a team this week and think it's best if we spin up our own implementations of the Universal Resolver (and potentially the registrar) as projects here, separate from the SDK.

**Comment by peacekeeper** [comment]
@decentralgabe Sounds great, I'd love to help with that if you need anything!

**Comment by andorsk** [comment]
Same here @peacekeeper and @decentralgabe . I'd love to help as well.

**Comment by pascaldekloe** [comment]
For HTTP I made a generic resolver, which applies some headers too. Feedback is welcome.

https://pkg.go.dev/github.com/pascaldekloe/did@v1.0.0/didweb#pkg-index

**Comment by decentralgabe** [comment]
this is done here https://github.com/TBD54566975/ssi-sdk/blob/main/did/resolver.go

will spin this out to a separate project/repo at some point in the coming months.

**Comment by andorsk** [comment]
@decentralgabe not sure what the plan is down the road, but wanted to ask what your thoughts are on the following: 

1. Try to resolve locally. 
2. If it doesn't resolve locally, use an external service ( i.e universal resolver ) to resolve as a fallback. Hyperledger Aries does this, and it seems like a reasonable approach. 

goal of the sdk should be to support as many functions internally as possible, as in general I'm not a huge fan of reaching outward to resolve a did, but it can resolve externally via an endpoint if needed as a fallback.

**Comment by peacekeeper** [comment]
+1 to the approach of first trying to resolve locally, and supporting the use of an external service as a fallback.

The external service should be configurable (i.e. don't just hardcode https://dev.uniresolver.io/ as the only possibility). Note also that there is both an HTTPS and a DIDComm binding for resolving via an remote service.

The list of locally resolvable DID methods should also be configurable; there may be situations where it's still preferable to use a remote resolver service, even if a local resolver also exists.

**Comment by decentralgabe** [comment]
Great idea @andorsk and agreed @peacekeeper. We have a resolver impl of this library code in the [ssi-service](https://github.com/TBD54566975/ssi-service/blob/main/internal/did/resolver.go#L11) but it does not do caching yet. We have yet to integrate an external service - but we have configuration where this can be set.

I'm opening an issue to make the resolver a caching resolver. https://github.com/TBD54566975/ssi-service/issues/237
