### ISSUE TITLE
Add Examples

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#39]
Create an examples package that demonstrates usage of all primitives exposed by the library. The examples do not need to be exhaustive, but instead a jumping-off point for those wishing to understand how they might use the library.

**Comment by andorsk** [comment]
+1 on this. Just wanted to note that it would help if these examples provided some context/references to edify themselves for people starting off with SSI. As an observation from someone just joining in on the project: I'm not sure yet exactly where to start. Perhaps another issue should be raised (or is this on the same issue), which gives a "walkthrough" for newbies.

**Comment by andorsk** [comment]
@decentralgabe can you assign this to me?

**Comment by decentralgabe** [comment]
Closing this in favor of specific example issues to be added.
