### ISSUE TITLE
IsValid should take in a context and return err

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-sdk#395]
The function below is hiding information from the users of the SDK, so it's difficult to understand what failed. The return type should be `error`.

Additionally, it should take in a `context.Context` as it's first parameter because it's doing a network lookup. 

It's debatable whether the name of the function should stay as `IsValid`. If returning an error, consider naming `Validate`. 

 https://github.com/TBD54566975/ssi-sdk/blob/a087372ee746be51c8ff7092490c95ba77835283/did/web/web.go#L32

**Comment by vlad-timofeev** [comment]
I have not been able to find usages of the function that have to be adjusted as the function signature changes, can you advise?

**Comment by andresuribe87** [comment]
Thanks for taking a look @vlad-timofeev !

There are no internal uses of this function. The SSI-service consumes this lib, so when it's updated, we'll need to make sure to also update the callers in there. 

For this issue I would recommend adding a unit test so we know this works as expected.

**Comment by vlad-timofeev** [comment]
Thank you for clarifying @andresuribe87 !

Created https://github.com/TBD54566975/ssi-sdk/pull/399

**Comment by vlad-timofeev** [comment]
@andresuribe87 is there anything else that should be updated to account for changes in #399 ?

**Comment by andresuribe87** [comment]
There isn't, thanks @vlad-timofeev !
