### ISSUE TITLE
[Bug] Docstring point to wrong file/line

### ISSUE THREAD

**Issue by haarts** [TBD54566975/ssi-sdk#408]
**Describe the bug**
This is a really trivial bug. I'm almost ashamed of submitting it.

In this example there's a reference to a file/line that no longer exists/is moved: https://github.com/TBD54566975/ssi-sdk/blob/main/example/did/did.go#L20. 
I think it should point here: https://github.com/TBD54566975/ssi-sdk/blob/main/did/key/key.go#L96

**To Reproduce**
n/a

**Expected behavior**
Clearly it should point to the right place.

**Supporting Material**
n/a

**Environment (please complete the following information):**

The issue is at least present in commit 989cdd25e04c3740dd87fbb00ef2ea8145d8eae4

**Comment by andresuribe87** [comment]
Thanks @haarts ! Fix is underway. We also accept PRs :)
