### ISSUE TITLE
[Bug] <failed run test>

### ISSUE THREAD

**Issue by huangzhiran** [TBD54566975/ssi-sdk#473]
**Describe the bug**

run 
`go run example/did/did.go` 
and get a error

`failed to expand did:key: could not construct JsonWebKey2020 verification method: could convert did:key to PublicKeyJWK: generating secp256k1 jwk: failed to initialize *jwk.ecdsaPublicKey from *ecdsa.PublicKey: invalid elliptic curve &{%!s(*elliptic.CurveParams=&{0x1400012e860 0x1400012e8a0 0x1400012e960 0x1400012e8e0 0x1400012e920 256 secp256k1})}exit status 1`

**Environment (please complete the following information):**

- OS: [e.g. MacOS]
- Version [13.5.2]
- GO [1.21.3]

**Comment by decentralgabe** [comment]
thanks for raising. this is being addressed here https://github.com/TBD54566975/ssi-sdk/pull/472
