### ISSUE TITLE
Support did:web

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#49]
https://w3c-ccg.github.io/did-method-web/

**Comment by singyiu** [comment]
Hi @decentralgabe 
would love to get a better understanding on the context of this issue.
i.e. 
Any did:web implementation we can take reference from, or we need to start from stretch with the specification ?
Does ssi-sdk need the full implementation of did:web, or just some selected features ?
Thanks

**Comment by decentralgabe** [comment]
Here's what I'm thinking (but feel free to tell me there's another perspective):
- [create a valid did:web document](https://w3c-ccg.github.io/did-method-web/#create-register), assuming one has a domain (take in those arguments...)
- [resolve a did:web document](https://w3c-ccg.github.io/did-method-web/#read-resolve) given a domain and return a Go object that can be turned into the JSON DID data model
- I don't believe [optional paths](https://w3c-ccg.github.io/did-method-web/#optional-path-considerations) need to be implemented to start with

Here's a reference impl linked to in the spec: https://github.com/decentralized-identity/web-did-resolver

**Comment by decentralgabe** [comment]
fixed in #116
