### ISSUE TITLE
Support Decentralized Web Node Messaging

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#62]
https://identity.foundation/decentralized-web-node/spec/#messages

**Comment by decentralgabe** [comment]
Partially handled in #210

**Comment by decentralgabe** [comment]
Need to add schema validation for schemas here - https://github.com/TBD54566975/dwn-sdk-js/tree/main/src/validation/json-schemas

**Comment by nitro-neal** [comment]
We dwn messages for now because this use case is now handled in the relay service
