### ISSUE TITLE
Create bindings for Java

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#67]
Test out Java bindings using cgo and JNA
See: 
- https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf
- https://developpaper.com/practice-summary-calling-go-code-in-java/
- https://github.com/freewind-demos/call-go-function-from-java-demo/blob/master/src/main/java/demo/types/GoString.java

Can also look at web assembly using https://github.com/wasmerio/wasmer-java

**Comment by hdou731** [comment]
I think I will probably just transcribe your work into java
