### ISSUE TITLE
Switch Packr to Embed

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk#85]
We use [packr](https://github.com/gobuffalo/packr). They recommend using [Go Embed](https://pkg.go.dev/embed). Let's make the switch.

**Comment by philippgille** [comment]
Hello :wave: , seeing Jack's tweet today I checked out the project and looked around the issues to see if there's any easy one for a quick contribution and found this one.

Here's the PR: https://github.com/TBD54566975/ssi-sdk/pull/101
